### PR TITLE
Add note about Django@3.0

### LINKED ISSUE #7: Add a note about Django@3.0
https://docs.djangoproject.com/en/3.1/ref/middleware/#referrer-policy

### PR DESCRIPTION
**Pull request by DmytroLitvinov**
Closes #7

### CODE REVIEW

**Comment by DmytroLitvinov** [comment]
Hi @sobolevn ,

Thank you for catching about default support from Django@3.0.
Could you please review and left your notes, ideas, thoughts?
I would appreciate it.

**Review by sobolevn — CHANGES_REQUESTED** [review]
Looks like you've pushed some artifacts

**Comment by DmytroLitvinov** [comment]
@sobolevn, fixed.
Also, [added line](https://github.com/DmytroLitvinov/django-http-referrer-policy/pull/8/files#diff-96d6e052f174c2a8855d5b21218211ac03e0da2a762712d68460823f8656fbc7R13) on checking Django's version.

**Review by sobolevn — APPROVED** [review]
Thanks!

**Pull request merged**
